# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 11:39
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hard_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('mask', models.CharField(max_length=16)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('config', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/storage/configs'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Toch_dost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='hardware',
            name='hard_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Types'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Hard_Model'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='toch_dost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Toch_dost'),
        ),
        migrations.AddField(
            model_name='hard_model',
            name='hard_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Types'),
        ),
        migrations.AddField(
            model_name='hard_model',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Manufacturer'),
        ),
    ]
