# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Регион'),
        ),
    ]
