# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_auto_20170715_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toch_dost',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Узел связи'),
        ),
    ]
