# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_auto_20170715_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='toch_dost',
            options={'verbose_name': 'Точка доступа', 'verbose_name_plural': 'Точки доступа'},
        ),
    ]
