# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 13:53
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_auto_20170715_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hard_model',
            options={'verbose_name': 'Модель устройства', 'verbose_name_plural': 'Модели устройств'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Марка', 'verbose_name_plural': 'Марки'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Тип устройства', 'verbose_name_plural': 'Типы устройств'},
        ),
        migrations.AlterModelOptions(
            name='ustr',
            options={'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterField(
            model_name='ustr',
            name='config',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/storage/configs'), upload_to='', verbose_name='Конфиг'),
        ),
        migrations.AlterField(
            model_name='ustr',
            name='hard_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Types', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='ustr',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='ustr',
            name='login',
            field=models.CharField(default='admin', max_length=20, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='ustr',
            name='mask',
            field=models.GenericIPAddressField(default='255.255.255.224', verbose_name='Маска'),
        ),
        migrations.AlterField(
            model_name='ustr',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Hard_Model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='ustr',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='ustr',
            name='toch_dost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Toch_dost', verbose_name='Узел свзяи'),
        ),
    ]
