# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_auto_20170715_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advanced_GW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='Внутренний IP')),
                ('white_ip', models.GenericIPAddressField(verbose_name='Белый IP')),
                ('pptp', models.CharField(max_length=100, verbose_name='PPTP')),
                ('pptp_password', models.CharField(max_length=100, verbose_name='PPTP Пароль')),
                ('ustr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hardware.Ustr', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Сетевые параметры',
                'verbose_name_plural': 'Сетевые параметры',
            },
        ),
    ]
